# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pilotbid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(verbose_name='bid open date')),
                ('close_date', models.DateTimeField(verbose_name='bid close date')),
            ],
        ),
        migrations.CreateModel(
            name='BidChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=10, verbose_name='choice')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(max_length=2, validators=[pilotbid.models.validate_status], verbose_name='status')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='submission time')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidSubmissionPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('bid_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.BidChoice')),
                ('bid_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.BidSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='BidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='BidTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50, verbose_name='option')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('option_true_false', models.BooleanField(verbose_name='option is true/false')),
                ('option_value', models.IntegerField(verbose_name='value')),
                ('bid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.BidType')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('ecrew_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ecrew ID')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorityListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_seniority', models.IntegerField(verbose_name='master seniority')),
                ('captain_seniority', models.IntegerField(verbose_name='captain seniority')),
                ('status', models.CharField(max_length=2, validators=[pilotbid.models.validate_status], verbose_name='status')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.Pilot')),
                ('seniority_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.SeniorityList')),
            ],
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.Pilot'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.BidType'),
        ),
        migrations.AddField(
            model_name='bid',
            name='seniority_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotbid.SeniorityList'),
        ),
    ]
